Feature 1
MiguelArgentina/members-only pull request #1
Opened 2021-03-19 17:56 UTC by MiguelArgentina

## In this project we implement authorization to our app
- Project specifications can be found in [The Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)
- This project implements authentication systems so users can only access areas and content of a site they are authorized to
- AUthentication was implemented using [Devise gem](https://github.com/heartcombo/devise)
- Tests were run to check the app before creating this PR
- We used application layout for sign-in and sign-out links
- Users can create their account using the `Become a member` link
- Users can have many posts but posts only belong to one user

2021-03-19 19:52 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @MiguelArgentina and @george-swift :clap: :clap:
#### Well done :muscle: you done a good job, the project looks great.
#### However, some requirements are missing/not implemented correctly. Check my comments below :point_down:

#### 1) Readme:
 - Add instruction on how to install dependencies and also database migration.

#### 2) View & Logic:
 - There should be NO application logic in the views use the helper method instead. Check these links for details [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code), [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers),

#### 3) Routes:
 - The application routes should be defined specifically for the used routes: `resources :posts, only: [:new, :create, :index]`

#### 4) PostController:
 - `new` action method should initialize an empty post `@post = Post.new`

#### _Reviewed by Temitayo Adeleke_

2021-03-19 19:52 UTC, lekegitrepo commented on app/views/layouts/_header.html.erb
> +          <% end %>
- remove logic from the view

2021-03-19 19:52 UTC, lekegitrepo commented on app/views/posts/_errors.html.erb
> +<% end %>
- remove logic from the view

2021-03-19 19:52 UTC, lekegitrepo commented on app/views/posts/index.html.erb
> +      <% end %>
- remove logic from the view

2021-03-19 22:57 UTC, george-swift commented on app/views/posts/_errors.html.erb
> +<% end %>
Requirements #2, #3 and #4 have been implemented. Helpers are particularly for removing complex logic from the views. Views should have as little embedded dynamic code as possible for clean, easy to modify and maintain code. However, the error messages are in a partial that is rendered in line 7 of `posts/new.html.erb`.  Writing a helper method in this case would only generate more markup.


<img width="1109" alt="Error_partial" src="https://user-images.githubusercontent.com/71434803/111848870-817d0880-890c-11eb-90db-76711314a64a.png">

2021-03-20 09:32 UTC, oloomoses requested changes
## Changes Required :recycle: 
**Hello team, you have done very well implementing the changes suggested by @lekegitrepo :muscle: 
Your project is amazing, however, there are some critical issues to fix before it can be approved :point_down:**
- [ ] As it is, a signed-in user is not able to sign-out. Kindly fix this.
- [x] `.idea` file is not part of the project file and should be moved to the `.gitignore` file

Kindly work on the above suggestions before submitting another review.
Feel free to leave a comment by mentioning me incase of doubts or concerns
_Slack: Oloo Moses_

2021-03-20 09:49 UTC, george-swift commented
A signed-in user can click on the Account link in the navbar. In the drop-down, there is a link to log out. Both sign-in and sign-out attempts if successful will trigger the devise alert notice. If a signed-in user wishes to cancel their account, they can access the cancel my account option in `edit profile` still in the dropdown. Again, a successful attempt will trigger a respective alert.


<img width="1299" alt="sign-in" src="https://user-images.githubusercontent.com/71434803/111865781-4fe65a80-8969-11eb-9d19-5c5a79226fa7.png">
<img width="1279" alt="sign-out" src="https://user-images.githubusercontent.com/71434803/111865783-5248b480-8969-11eb-95b1-816b124a09de.png">

2021-03-20 15:06 UTC, GzimAsani requested changes
# STATUS: Changes Required :red_circle: 

### Hello team, great job implementing all the changes asked previously but still one of them has to be implemented which was asked previously:
- [ ] The `Account` dropdown is not working therefore a user cannot logout so please fix this

Please fix the required changes and ask for another code review whenever you're ready

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

2021-03-20 17:45 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-03-20 20:06 UTC, merged